options:
  # Minimum distance out from the main island you can get teleported
  min_radius: 5100
  # Maximum distance from the main island you can get teleported
  max_radius: 5300
  # Number of attempts to try and teleport
  max_attempts: 10
  # Minimum Y level of the end stone island. player will be standing at that height +3
  min_island_y: 140
  # Max height of end stone island
  max_island_y: 180
  # Radius of the end stone island
  island_radius: 5
  # thickness of the end stone_island
  island_thickness: 3
  # Amount of air blocks above island
  air_gap: 3